[book]
authors = ["caukub"]
language = "en"
src = "src"
multilingual = false
title = "caukub's Minecraft Server Handbook"

[build]
create-missing = false

[output.html]
additional-css = ["assets/hints.css"]
additional-js = ["assets/hints.min.js", "assets/popperjs-core.min.js", "assets/tippy.min.js"]
mathjax-support = false
no-section-label = false
smart-punctuation = true
git-repository-url = "https://github.com/caukub/mcgui-de"
git-repository-icon = "fa-github"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 2

[output.html.print]
enable = false

[preprocessor.hints]

[preprocessor.alerts]